#pragma once

#define STACKCHAN_DEVICE_PAPERMONO 1
#define STACKCHAN_HAS_NFC 1

#ifndef PAPER_MONO_RELEASE_VERSION
#define PAPER_MONO_RELEASE_VERSION "dev"
#endif

#define STEP_COUNTER_ENABLED 1
#define STEP_COUNTER_HISTORY_DAYS 30
#define STEP_COUNTER_DAY_START_HOUR 0
#define STEP_COUNTER_SAVE_STEP_DELTA 10
#define STEP_COUNTER_SAVE_INTERVAL_MS 60000
#define STEP_COUNTER_STEP_SCALE_NUMERATOR 1
#define STEP_COUNTER_STEP_SCALE_DENOMINATOR 1
#define STEP_COUNTER_WALK_START_CANDIDATES 3
#define STEP_COUNTER_MIN_STEP_INTERVAL_MS 280
#define STEP_COUNTER_MAX_STEP_INTERVAL_MS 1500
#define STEP_COUNTER_WALKING_TIMEOUT_MS 2000
#define STEP_COUNTER_DYNAMIC_ENERGY_MULTIPLIER 2.6f
#define STEP_COUNTER_DYNAMIC_ENERGY_MIN 0.020f
#define STEP_COUNTER_LOW_THRESHOLD_RATIO 0.42f
#define STEP_COUNTER_MAGNITUDE_RISE_ONLY 1
#define STEP_COUNTER_SAMPLE_GAP_RESET_MS 500
#define STEP_COUNTER_DIAG_LOG_ENABLED 0
#define STEP_COUNTER_DIAG_LOG_INTERVAL_MS 5000

#define PAPER_MONO_DEFAULT_STEP_GOAL 10000UL
#define PAPER_MONO_MIN_STEP_GOAL 1000UL
#define PAPER_MONO_MAX_STEP_GOAL 50000UL
#define PAPER_MONO_STEP_GOAL_INCREMENT 1000UL

#define PAPER_MONO_FRONT_LIGHT_BRIGHTNESS 64
#define PAPER_MONO_LOCKED_UPDATE_MS 60000UL
#define PAPER_MONO_NFC_WAIT_TIMEOUT_MS 60000UL
#define PAPER_MONO_FULL_REFRESH_AFTER_PARTIALS 10
#define PAPER_MONO_IMU_SAMPLE_INTERVAL_MS 20UL
#define PAPER_MONO_LOW_POWER_CPU_MHZ 80
