[platformio]
default_envs = paper-mono

[env:paper-mono]
platform = espressif32 @ 6.12.0
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

board_build.partitions = partitions_16mb_ota_4m_littlefs_7m.csv
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi

extra_scripts =
  pre:scripts/embed_default_image.py
  pre:scripts/patch_m5unit_nfc.py

build_flags =
  -D ESP32S3
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D UART_SCLK_DEFAULT=UART_SCLK_APB
  -D PAPER_MONO_NFC_IMAGE_TRANSFER=1
  -D STACKCHAN_DEVICE_PAPERMONO=1
  -D STACKCHAN_HAS_NFC=1
  -std=gnu++17

build_unflags =
  -std=gnu++11

lib_deps =
  m5stack/M5Unified @ 0.2.20
  m5stack/M5GFX @ 0.2.27
  bblanchon/ArduinoJson @ 7.4.3
  https://github.com/m5stack/M5PM1.git#be9a5456c007c333e7ac963f33bfde1ffa5d82ee
  https://github.com/m5stack/M5IOE1.git#846eec7d05e25c09013be2acdb8804487f48a62e
  m5stack/M5UnitUnified @ 0.5.0
  https://github.com/m5stack/M5Unit-NFC.git#0.1.0
